# Generated by Django 2.2 on 2021-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
